name: downclim
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - aenum
  - dask
  - earthengine-api
  - esgf-pyclient
  - gcsfs
  - ipykernel
  - multiprocess
  - netcdf4
  - pydantic
  - pygadm
  - rioxarray
  - xesmf
  - xee
  - zarr
