# file generated by setuptools_scm
# don't change, don't track in version control
from __future__ import annotations

TYPE_CHECKING = False
if TYPE_CHECKING:  # noqa: SIM108
    VERSION_TUPLE = tuple[int | str, ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "0.1.dev77+gf7b2f80.d20250117"
__version_tuple__ = version_tuple = (0, 1, "dev77", "gf7b2f80.d20250117")
