# Area
proj_crs: "default"

# Time
time_frequency: "mon"
hist_years: ["1980-2005"]
eval_years: ["2006-2019"]
proj_years: ["2071-2100"]

# Variables
variables: ["tas", "tasmin", "tasmax", "pr"]

# Baseline
baseline: "chelsa2"
base_years: ["1980-2019"]

# Projection
projections: "config/projections_ex.tsv"
esgf_years: ["1980-2100"]

# Downscaling
ds_method: "bc"

# Evaluation
base_eval: "chelsa2"
log10_eval_pts: 4

# Ensemble
ens_method: "sma"
