area: "New Caledonia"
baseline: "CHELSA V2.1"
hist_years: [1980, 2005]
eval_years: [2006, 2013]
proj_years: [2071-2100]
domain: "AUS-22"
gcm: ["ECMWF-ERAINT", "MOHC-HadGEM2-ES", "MPI-M-MPI-ESM", "NCC-NorESM1-M"]
rcm: ["CCLM5-0-15", "REMO2015", "RegCM4-7"]
rcp: ["historical", "rcp26", "rcp85"]
