__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"

get_area:
  jobname: "get_area"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

get_chelsa2:
  jobname: "get_chelsa2"
  mem: "20G"
  cpus: 10
  time: "24:00:00"

get_cmip6:
  jobname: "get_cmip6"
  mem: "20G"
  cpus: 10
  time: "24:00:00"

get_cordex:
  jobname: "get_cordex"
  mem: "20G"
  cpus: 10
  time: "24:00:00"

downscale_bc:
  jobname: "downscale_bc"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

hist_base:
  jobname: "hist_base"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  
hist_proj:
  jobname: "hist_proj"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  
eval_proj:
  jobname: "eval_proj"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  
merge_hist:
  jobname: "merge_hist"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  
merge_eval:
  jobname: "merge_eval"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  