__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  
get_area:
  jobname: "get_area"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

get_proj:
  jobname: "get_proj"
  mem: "20G"
  cpus: 1
  time: "01:00:00"

get_chelsa2:
  jobname: "get_chelsa2"
  mem: "20G"
  cpus: 1
  time: "01:00:00"
  
downscale_bc:
  jobname: "downscale_bc"
  mem: "20G"
  cpus: 1
  time: "01:00:00"
  
evaluate_bc:
  jobname: "evaluate_bc"
  mem: "20G"
  cpus: 1
  time: "01:00:00"
