__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  
aggregate_base:
  jobname: "aggregate_base"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

aggregate_proj:
  jobname: "aggregate_proj"
  mem: "10G"
  cpus: 1
  time: "01:00:00"
  
downscale_bc:
  jobname: "downscale_bc"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

get_area:
  jobname: "get_area"
  mem: "10G"
  cpus: 1
  time: "01:00:00"

get_chelsa2:
  jobname: "get_chelsa2"
  mem: "20G"
  cpus: 10
  time: "01:00:00"

get_cmip6:
  jobname: "get_cmip6"
  mem: "20G"
  cpus: 10
  time: "01:00:00"

get_cordex:
  jobname: "get_cordex"
  mem: "20G"
  cpus: 10
  time: "01:00:00"
